# -*- coding: utf-8 -*-
"""submission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r3iI-1UiV8b3Gx-nuGeJnm_8rj_g4iap

# COE 292 — Assignment 2

## Topic: Neural Networks

This assignment is divided into two sections:
* Problem I [60 Points]
  * You will develop a **Neural Network** to model a Smart AC On/Off Function that decides whether to turn an air conditioner **ON (1)** or **OFF (0)** automatically.


* Problem II [30 Points]
  * You will train and develop a neural network, using Keras, to classify images from Fashion-MNIST dataset
---

# Problem I [60 Points]

There are three parts to Problem I: Part A, Part B and Part C

* You must implement a neural network logic yourself using **Python + NumPy** following the instructions provided in the respective cells.

* The decision to turn AC on or off depends on real-life factors:

    * Temperature (°C)  
    * Humidity (%)  
    * Time of day (Day / Night)  
    * Occupancy (No/Yes)
    * Electricity cost (Low / High)

  

## Input and Output Description

#### Inputs (Features)

| Symbol | Feature | Type | Example |
|--------|---------|------|---------|
| x1 | Temperature (°C) | continuous | 32.5 |
| x2 | Humidity (%) | continuous | 70 |
| x3 | Time of day (0 = Night, 1 = Day) | binary | 1 |
| x4 | Occupancy (0 = No, 1 = Yes) | binary | 0 |
| x5 | Electricity cost (0 = Low, 1 = High) | binary | 0 |

#### Output

| y | Meaning |
|---|---------|
| 1 | Turn AC ON |
| 0 | Turn AC OFF |

---

## Part A: Dataset Setup

* Read the instructions and do as instructed

* Step 1:
  * Enter your 9-digit KFUPM Student ID # to save in STUDENT_ID
  * Then, simply run the cell.

* Step 2
  * Run the Step 2 cell to generate synthetic data to be used for your assignment (No code to modify here)

**Part A: Step 1**
"""

import numpy as np
import matplotlib.pyplot as plt

#TO DO
STUDENT_ID =  202358970 # Enter your 9-digit KFUPM Student ID


TO_PLOT = True # Set this to False when submitting

"""**Part A: Step 2**"""

# RUN THIS CELL AS IS
# DO NOT MODIFY THE CODE IN THIS CELL

np.random.seed(STUDENT_ID)

# Number of samples
N = 200

# Ranges based on STUDENT_ID
T1 = min(STUDENT_ID%100, int(STUDENT_ID/100)%100) # 6th, 7th digits # 8th, 9th digits
T2 = max(STUDENT_ID%100, int(STUDENT_ID/100)%100)
H1 = min(int(STUDENT_ID/10000)%100, int(STUDENT_ID/1000000)%100) # 4th, 5th digits # 2nd, 3rd digits
H2 = max(int(STUDENT_ID/10000)%100, int(STUDENT_ID/1000000)%100)

# Continuous features
temp = np.random.uniform(T1, T2, size=(N, 1))    # °C
hum  = np.random.uniform(H1, H2, size=(N, 1))    #  %

# Binary features
time_day  = np.random.randint(0, 2, size=(N, 1))   # 0 night, 1 day
occupancy = np.random.randint(0, 2, size=(N, 1))   # 0 no, 1 yes
cost_high = np.random.randint(0, 2, size=(N, 1))   # 0 low, 1 high

# Stack into X_raw
X_raw = np.hstack([temp, hum, time_day, occupancy, cost_high])

# Human rule for labels
temp_high = (temp >= T1).astype(int)
hum_high  = (hum  >= H1).astype(int)

# This sets the ground truth based on a custom rule
y = ((occupancy == 1) & ((temp_high == 1) | (hum_high == 1)) & (cost_high == 0)).astype(int)

# print("X_raw shape:", X_raw.shape)
# print("y shape:", y.shape)
# print("First 5 samples (temp, hum, time, occ, cost):")
# print(X_raw[:5])
# print("First 20 labels:", y[:20].reshape(-1))

### Simple scaling of continuous features (optional but helpful for MLP)
# Scale only the first two columns (temp, hum) to [0, 1] roughly
X = X_raw.astype(float).copy()

X[:, 0] = (X[:, 0] - T1) / (T2 - T1)   # temperature
X[:, 1] = (X[:, 1] - H1) / (H2 - H1)   # humidity

# print("Scaled X first 5 rows:")
# print(X[:5])

"""## Part B — One-Hidden-Layer Neural Network (H = 4)

* Design and implement a **1-hidden-layer Neural Network**:

  ```text
  5 inputs → H hidden neurons in the hidden layer → 1 output
  ```

* Constraints
  - Hidden layer neurons: **H = 4**  
  - Hidden layer activation: **ReLU**
  - Output layer activation: **sigmoid**
  - Loss function: **Mean Squared Error (MSE)**  

---

* Step 1
  * TO DO: Implement activation functions and loss functions

* Step 2 (Parameters Initialization)
  * No code to modify here, simply run the Parameters Initialization cell to randomly initialize the weights and biases for your neural network

* Step 3 (Implement Forward Pass)
  * TO DO: Complete the code to implement the forward pass

* Step 4 (Implement Backpropagation)
  * TO DO: Complete the code to implement Backpropagation using MSE loss

* Step 5 (Training Loop)
  * No code to modify/add here, simply run the cell

####Part B: Step 1 - Implement Activation functions and loss [20 Points]

  * B.1 Task1: Implement ReLU activation function [5 Points]
  * B.1 Task2: Implement function to compute ReLU derivative [5 Points]
  * B.1 Task3: Implement Sigmoid activation function [5 Points]
  * B.1 Task4: Implement Mean Squared Error (MSE) Loss function [5 Points]

  Note: Each function takes 'z' as the only input
"""

# B.1 Task 1
def relu(z):
    res =  z * (z > 0) # TO DO
    return res

# B.1 Task 2
def relu_derivative(z):
    res =  1 * (z > 0) # TO DO   # is 1 where z > 0, else 0
    return res

# B.1 Task 3
def sigmoid(z):
    # Clip to avoid overflow
    z = np.clip(z, -50, 50)

    res =   1 / (1 + np.exp(-z)) # TO DO
    return res

# B.1 Task 4
def mse_loss(y_true, y_pred):
    res =  np.mean((y_true - y_pred)**2) # TO DO
    return res

"""#### Part B: Step 2 - Parameter Initialization

"""

# Simply run the cell to initialize parameters
# DO NOT MODIFY THIS CELL

def init_params(input_dim=5, hidden_dim=4, output_dim=1):
    # Small random weights, zero biases
    W1 = 0.1 * np.random.randn(input_dim, hidden_dim)
    b1 = np.zeros((1, hidden_dim))
    W2 = 0.1 * np.random.randn(hidden_dim, output_dim)
    b2 = np.zeros((1, output_dim))

    return {"W1": W1, "b1": b1, "W2": W2, "b2": b2}

"""#### Part B: Step 3 - Implement Forward Pass [10 Points]

Complete the code in the cell below
"""

def forward_pass(X, params): # Do not change this line, do not change the variable names
    W1, b1 = params["W1"], params["b1"] # Do not change this line
    W2, b2 = params["W2"], params["b2"] # Do not change this line


    z1 =      X @ W1 + b1       # TO DO B.3 Task 1 (Output from Layer 1 before applying activation function) # (N, 4)
    a1 =      relu(z1)       # TO DO B.3 Task 2 (Output from Layer 1 after applying activation function) # (N, 4)
    z2 =        a1 @ W2 + b2      # TO DO B.3 Task 3 (Output from Layer 2 before applying activation function) # (N, 1)
    y_hat =     sigmoid(z2)     # TO DO B.3 Task 4 (Output from Layer 2 after applying activation function) # (N, 1)

    cache = {"X": X, "z1": z1, "a1": a1, "z2": z2, "y_hat": y_hat} # Do not change this line

    return y_hat, cache # Do not change this line

"""#### Part B: Step 4 - Implement Backpropagation using Mean Squared Error (MSE) loss [10 Points]

Complete the code in the cell below (see TO DO lines)
"""

def backward_pass(y_true, params, cache): # Do not change this line, do not change variable names
    W2 = params["W2"]

    X   = cache["X"]
    z1  = cache["z1"]
    a1  = cache["a1"]
    y_hat = cache["y_hat"]

    N = X.shape[0]


    d_yhat = (2/N) * (y_hat - y_true) # TO DO B.4 Task 1 - Derivative of MSE Loss with respect to y_hat

    d_z2 = d_yhat * y_hat * (1 - y_hat) # TO DO B.4 Task 2 : (Derivative of y_hat with respect to z2) * (Upstream Gradient)

    dW2 =  a1.T @ d_z2 # TO DO B.4 Task 3 : (Derivative of z2 with respect to W2) * (Upstream Gradient)

    db2 = np.sum(d_z2, axis=0, keepdims=True)  # Do not change this line

    # Backprop into hidden layer
    d_a1 = d_z2 @ W2.T                         # (N, H) # Do not change this line
    d_z1 = d_a1 * relu_derivative(z1)          # (N, H) # Do not change this line

    # z1 = X @ W1 + b1
    dW1 = X.T @ d_z1                           # (5, H)
    db1 = np.sum(d_z1, axis=0, keepdims=True)  # (1, H)

    grads = {"dW1": dW1, "db1": db1, "dW2": dW2, "db2": db2}
    return grads

"""#### Part B: Step 5 - Training loop (full-batch gradient descent) [10 Points]

* Complete the code in the cell below (see TO DO lines)
* Do not change any other lines of code
"""

# This function has the training code

def train_nn(X, y, lr=0.1, epochs=2000, print_every=200):
    params = init_params(input_dim=X.shape[1], hidden_dim=4, output_dim=1)
    losses = []

    for epoch in range(epochs):
        # Forward
        y_hat, cache = forward_pass(X, params)

        # Loss
        loss = mse_loss(y, y_hat)
        losses.append(loss)

        # Backward
        grads = backward_pass(y, params, cache)

        # Gradient descent update
        params["W1"] = params["W1"] - lr * grads["dW1"] # TO DO B.5 Task 1 (update params["W1"])
        params["b1"] = params["b1"] - lr * grads["db1"]  # TO DO B.5 Task 2 (update params["b1"])
        params["W2"] = params["W2"] - lr * grads["dW2"] # TO DO B.5 Task 3 (update params["W2"])
        params["b2"] =  params["b2"] - lr * grads["db2"]# TO DO B.5 Task 4 (update params["b2"])

        if epoch % print_every == 0 or epoch == epochs - 1:
            print(f"Epoch {epoch:4d} | MSE loss = {loss:.6f}")

    return params, np.array(losses) # Do not change

"""## Part C: Train and Evaluate the Neural Network

  * Step 1 - Train the Neural Network [5 Points]
    * Run Step 1 code for sufficient number of epochs (max. 100), using sufficient learning rate 'l_rate' to get an accuracy of > 90%
  * Step 2 - Evaluate the Neural Network [5 Points]
    * Complete the code to calculate number of True Positives (TP), True Negatives (TN), False Positives (FP), and False Negatives (FN)

#### Part C: Step 1 - Train the Neural Network [5 Points]

* Train the model for a sufficient number of epochs such that model accuracy is > 90%
"""

l_rate = 0.1 # TO DO Part C Task 1 - change this as needed
n_epochs = 1000 # TO DO Part C Task 1- change this as needed, to get model accuracy > 90%
params, losses = train_nn(X[:-50,:], y[:-50], lr=l_rate, epochs=n_epochs, print_every=400)

if TO_PLOT is True:
  plt.figure()
  plt.plot(losses)
  plt.xlabel("Epoch")
  plt.ylabel("MSE loss")
  plt.title("Training loss")
  plt.show()

"""#### Part C: Step 2 - Evaluate the Neural Network [5 Points]

* TO DO: Complete the code to calculate number of True Positives (TP), True Negatives (TN), False Positives (FP), and False Negatives (FN)

* Your model must achieve an accuracy > 90% to get the score for Part C
"""

X_test = X[150:,:]
y_test = y[150:]

y_hat, _ = forward_pass(X_test, params)
y_pred = (y_hat >= 0.5).astype(int) # Do not change

acc_mlp = (y_pred.reshape(-1) == y_test.reshape(-1)).mean()
print("MLP accuracy:", acc_mlp)

TP = np.sum((y_test.reshape(-1) == 1) & (y_pred.reshape(-1) == 1)) # TO DO Part C Task 2 (Code to compute number of True Positives)
TN = np.sum((y_test.reshape(-1) == 0) & (y_pred.reshape(-1) == 0))# TO DO Part C Task 2 (Code to compute number of True Negatives)
FP = np.sum((y_test.reshape(-1) == 0) & (y_pred.reshape(-1) == 1))# TO DO Part C Task 2 (Code to compute number of False Positives)
FN = np.sum((y_test.reshape(-1) == 1) & (y_pred.reshape(-1) == 0))# TO DO Part C Task 2 (Code to compute number of False Negatives)

print("\nConfusion Matrix (rows: true, columns: predicted)")
print("      pred0  pred1")
print(f"true0  {TN:4d}  {FP:4d}")
print(f"true1  {FN:4d}  {TP:4d}")

"""# Problem II [20 Points]

You will develop a neural network-based image classifier using Keras

The dataset to use for this Problem II is the Fashion-MNIST dataset which contains images of 10 classes

There are three parts to Problem II: Part A, Part B and Part C. Read all instructions and steps carefully and complete the tasks.

### Part A: Setup


Simply run the cell below to do the imports
"""

import tensorflow as tf
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.datasets import fashion_mnist
import matplotlib.pyplot as plt
import numpy as np
import sklearn as sk

"""### Part B: Data Loading and Pre-processing

* Run the cell below which prepares:
  * x_train_flat : x_train images data converted to 1D
  * y_train : ground truth class labels for the images in x_train_flat
  * x_val_flat : x_val images data converted to 1D
  * y_val : ground truth class labels for the images in x_val_flat
  * x_test_flat : x_test images data converted to 1D
  * y_test : ground truth class labels for the images in x_test_flat
"""

# Do not modify code in this cell,
# You just need to run this cell

def train_val_split(x, y, val_ratio=0.2, seed=None):

    assert len(x) == len(y), "x and y must have same number of samples"

    N = len(x)

    # random seed
    if seed is not None:
        np.random.seed(seed)

    # Shuffle indices
    indices = np.random.permutation(N)

    # Split point
    val_size = int(N * val_ratio)

    val_idx = indices[:val_size]
    train_idx = indices[val_size:]

    # Make splits
    x_val = x[val_idx]
    y_val = y[val_idx]

    x_train = x[train_idx]
    y_train = y[train_idx]

    return x_train, y_train, x_val, y_val


# (x_train, y_train), (x_test, y_test) = cifar10.load_data()
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

x_train = x_train / 255.0
x_test = x_test / 255.0

x_train, y_train, x_val, y_val = train_val_split(x_train, y_train, val_ratio=0.2, seed=STUDENT_ID)

x_train_flat = x_train.reshape((x_train.shape[0], -1))
x_val_flat = x_val.reshape((x_val.shape[0], -1))
x_test_flat  = x_test.reshape((x_test.shape[0], -1))

"""### Part C: Step 1 - Model Implementation (using Keras) [10 Points]

Make a fully connected feedforward neural network using Keras to classify the given images into one of ten classes, following the instructions below:
* Use ReLU activation function for hidden layers (you may use other activation functios if needed to enhance the model's accuracy)
* Use softmax activation function for the output layer
* Use 'adam' optimzier
* Employ the 'sparse_categorical_crossentropy' loss function
* Use 'accuracy' as the metric when compiling the model
* Your model must achieve an accuracy of > 85% on the test set to get the score for Section II Part C.
  * Hint: To enhance the accuracy, consider adding more layers and/or adding more neurons per layer (Increasing Model Complexity)


Complete the code in the cell below (see TO DO lines)
"""

# Model
model_ce = models.Sequential([
    layers.Flatten(),                     # flatten image input
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
    ])  # TO DO Part C.1 Task 1
model_ce.compile( optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']) # TO DO Part C.1 Task 2

model_ce.summary() # to print the model design

"""### Part C: Step 2 -Training and validation of the model

The model_ce.fit(...) call will train your model for NEpochs number of epochs, and evaluate the model in each epoch on a validation set (20% of the training set).

* You may change `NEpochs` as needed (max NEpochs allowed is 100)
* You may vary `batch_size` as needed
* Do not change `validation_data`

The accuracy on the validation set will be printed as the code in the cell below is running.

In Part C: Step 3, you will evaluate the trained model on the test set. Your model must achieve an accuracy > 85% on the test set to get the score for this task
"""

NEpochs = 10 # Change as needed

history_ce = model_ce.fit(x_train_flat, y_train, epochs=NEpochs, batch_size=32, validation_data=(x_val_flat, y_val))

# You may change NEpochs and batch_size, but do not change validation_data

"""### Part C: Step 3 - Evaluate the model on the test set [10 Points]

Run the code in the cell below to test your model on the test set and see the accuracy on the test set.

You dont need to modify any code below

**Your model must achieve an accuracy of > 85% on the test set to get the score for Problem II, Part C - Step 3. The maximum NEpochs could be 100, i.e., your model must not need training beyond 100 epochs to achieve the >85% accuracy on the test set**
"""

test_loss_ce, test_acc_ce = model_ce.evaluate(x_test_flat, y_test)
print(f'Test Accuracy: {test_acc_ce:.4f}')

